export const notifications = [
  {
    created_at: "2019-03-24T10:24:32.495Z",
    data: {
      display_username: "janedoe",
      original_post_id: 41,
      original_post_type: 1,
      original_username: "janedoe",
      revision_number: null,
      topic_title: "Hello, I'm Jane Doe",
    },
    fancy_title: "Hello, I&rsquo;m Jane Doe",
    id: 18,
    notification_type: 6,
    post_number: 1,
    read: false,
    slug: "hello-im-jane-doe",
    topic_id: 26,
  },
  {
    created_at: "2019-03-24T10:37:18.891Z",
    data: {
      display_username: "system",
      group_id: 1,
      topic_title: "Backup failed",
    },
    fancy_title: "Backup failed",
    id: 1,
    notification_type: 7,
    post_number: 1,
    read: false,
    slug: "backup-failed",
    topic_id: 11,
  },
  {
    created_at: "2019-03-24T11:24:32.495Z",
    data: {
      display_username: "janedoe",
      original_post_id: 42,
      original_post_type: 1,
      original_username: "janedoe",
      revision_number: null,
      topic_title: "Elephant",
    },
    fancy_title: "Elephant",
    id: 19,
    notification_type: 5,
    post_number: 1,
    read: false,
    slug: "hello-im-jane-doe",
    topic_id: 26,
  },
];
